/*
 * N/A
 * N/A
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.aardwark.players.api;

import org.openapitools.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PlayerApi
 */
@Ignore
public class PlayerApiTest {

    private final PlayerApi api = new PlayerApi();

    
    /**
     * N/A
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void activePlayerListGetTest() throws ApiException {
        String refdate = null;
        String windowsize = null;
        String response = api.activePlayerListGet(refdate, windowsize);

        // TODO: test validations
    }
    
    /**
     * N/A
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void playerAPlayerCodeGetTest() throws ApiException {
        String aplayerCode = null;
        String response = api.playerAPlayerCodeGet(aplayerCode);

        // TODO: test validations
    }
    
}
