package com.modeler.test;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import com.application.PlayersModeler;

import static org.junit.Assert.*;

public class MainTest {
    @Test 
    public void testSomeLibraryMethod() {
        //Main classUnderTest = new Main();
        assertTrue("someLibraryMethod should return 'true'", PlayersModeler.generateBwfTSApplication());
        
        // Check data model is generated
        
    }
}
